version: "2.4"

services:
  odoo_proxy:
    image: tecnativa/whitelist
    depends_on:
      - odoo
    networks: &public
      default:
      public:
    ports:
      - "172.25.252.10:89:6899"
      - "172.25.252.10:80:8069"
    environment:
      PORT: "6899 8069"
      TARGET: odoo
      ODOO_HTTP_SOCKET_TIMEOUT: 10

  odoo:
    extends:
      file: common.yaml
      service: odoo
    restart: unless-stopped
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      INITIAL_LANG: "es_ES"
      PYTHONPATH: /opt/odoo/custom/src/odoo
    depends_on:
      - db
    networks:
      default:
    labels:
      doodba.domain.main: ""

db:
    extends:
      file: common.yaml
      service: db
    environment:
      CONF_EXTRA: |
        work_mem = 4915kB
        max_connections = 1500
        shared_buffers = 3840MB
        effective_cache_size = 11520MB
        maintenance_work_mem = 960MB
        checkpoint_completion_target = 0.9
        wal_buffers = 16MB
        default_statistics_target = 100
        random_page_cost = 1.1
        effective_io_concurrency = 200
        min_wal_size = 2GB
        max_wal_size = 8GB
        max_worker_processes = 12
        max_parallel_workers_per_gather = 4
        max_parallel_workers = 12
    env_file:
      - .docker/db-creation.env
    restart: unless-stopped

networks:
  default:
    driver_opts:
      encrypted: 1
  public:

volumes:
  filestore:
  db:
